import {
  MANAGE_SESSIONS_SEARCH_ENTRIES,
  TERMINAL_ADVANCED_SEARCH_ENTRIES,
  TERMINAL_CURSOR_SEARCH_ENTRIES,
  TERMINAL_DARK_THEME_SEARCH_ENTRIES,
  TERMINAL_FLOATING_SEARCH_ENTRIES,
  TERMINAL_GHOSTTY_IMPORT_SEARCH_ENTRIES,
  TERMINAL_LIGHT_THEME_SEARCH_ENTRIES,
  TERMINAL_MAC_OPTION_SEARCH_ENTRIES,
  TERMINAL_PANE_STYLE_SEARCH_ENTRIES,
  TERMINAL_QUICK_COMMANDS_SEARCH_ENTRIES,
  TERMINAL_RENDERING_SEARCH_ENTRIES,
  TERMINAL_SETUP_SCRIPT_SEARCH_ENTRIES,
  TERMINAL_TYPOGRAPHY_SEARCH_ENTRIES,
  TERMINAL_WINDOW_SEARCH_ENTRIES
} from './terminal-search'
import { TERMINAL_WINDOWS_SEARCH_ENTRIES } from './terminal-windows-search'
import type { SettingsSearchEntry } from './settings-search'

export function getTerminalPaneSearchEntries(platform: {
  isWindows: boolean
  isMac: boolean
}): SettingsSearchEntry[] {
  // Why: keep search results aligned with the controls each platform actually renders.
  return [
    ...TERMINAL_TYPOGRAPHY_SEARCH_ENTRIES,
    ...TERMINAL_FLOATING_SEARCH_ENTRIES,
    ...TERMINAL_QUICK_COMMANDS_SEARCH_ENTRIES,
    ...TERMINAL_RENDERING_SEARCH_ENTRIES,
    ...TERMINAL_CURSOR_SEARCH_ENTRIES,
    ...TERMINAL_PANE_STYLE_SEARCH_ENTRIES,
    ...(platform.isWindows ? TERMINAL_WINDOWS_SEARCH_ENTRIES : []),
    ...TERMINAL_DARK_THEME_SEARCH_ENTRIES,
    ...TERMINAL_LIGHT_THEME_SEARCH_ENTRIES,
    ...TERMINAL_WINDOW_SEARCH_ENTRIES,
    ...TERMINAL_SETUP_SCRIPT_SEARCH_ENTRIES,
    ...TERMINAL_GHOSTTY_IMPORT_SEARCH_ENTRIES,
    ...MANAGE_SESSIONS_SEARCH_ENTRIES,
    ...TERMINAL_ADVANCED_SEARCH_ENTRIES,
    ...(platform.isMac ? TERMINAL_MAC_OPTION_SEARCH_ENTRIES : [])
  ]
}
